[tool.poetry]
name = "auth_service"
version = "0.1.0"
description = ""
authors = ["Michal Lecbych <pasacek@qualityregistry.org>"]

[tool.poetry.dependencies]
python = "~3.10"
httpx = "^0.23.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
